apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
  namespace: spinnaker-operator
spec:
  spinnakerConfig:
    config:
      version: 1.31.0
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: spinnaker
          rootFolder: front50
          endpoint: http://minio.minio.svc.cluster.local:9000
          pathStyleAccess: true
          accessKeyId: minio
          secretAccessKey: minio123
          region: us-east-1
  expose:
    type: NodePort
